[package]
name = "FerrumWeb"
version = "0.1.1"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.24", features = ["blocking"]}
scraper = "0.24.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
